### PR TITLE
9 user auth

### LINKED ISSUE #9: User Authentication
As a user
so that my details and reviews are tied to me
I would like to be able to sign up and log in.

### PR DESCRIPTION
**Pull request by alterenzo**
Closes #9

### CODE REVIEW

**Comment by mbutlerw** [comment]
As a user
so that i know if i am logged in or not
I would like to see some indication of my sessions status.

**Comment by mbutlerw** [comment]
Closes #10

**Comment by mbutlerw** [comment]
:shipit:

**Comment by Andy-Bell** [comment]
:shipit:

**Pull request merged**
